version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ default port
      - "15672:15672"   # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    hostname: rabbitmq

volumes:
  rabbitmq_data:
